"""Pictures for a piece — always the knowledge graph first, so nothing is fetched or generated twice.

- Logos: graph -> Wikimedia Commons (public domain, CC0, CC BY, CC BY-SA; logos, seals, emblems, crests, wordmarks) -> the
  entity's own website / brand or press kit (found with Codex web search, downloaded only from its own domain or CDN).
- Press images (products, venues, packshots): graph -> the entity's official newsroom / press kit via Codex web search.
- Official galleries: every real image on the story's official pages (announcement, newsroom, press kit, product page) —
  screenshots, product shots, key art, official photos — vision-labelled, registered for reuse, credited "Images: <owner>".
- Real photos: named people/places/teams: graph -> Wikimedia Commons -> Openverse (PD / CC0 / CC BY / CC BY-SA, credited);
  generic subjects (a stadium, a phone, an office, food): graph -> Unsplash / Pexels / Pixabay (free commercial licences) -> Commons.
- Objects: graph (a similar prompt) -> generated by Codex on flat green and cut out.
Never (credit is not a licence for these; Rights Manager strikes them): agency or wire photos (Getty, AP, Reuters, PTI,
Sportzpics, Shutterstock…), news-site photos, broadcast frames — unless the owner buys a licence and it is wired in.
Every new file is registered in the graph with its source, licence and the entity it depicts.
Contact sheets: one frame per second of a rendered video, for the picture editor.
"""
import json, pathlib, re, subprocess, tempfile, urllib.error, urllib.parse, urllib.request
import numpy as np
from PIL import Image, ImageDraw, ImageFont
from . import graph, llm
from .config import TOOLS, PUBLIC

UA = {"User-Agent": f"StudioBot/1.0 ({PUBLIC}; editorial media lookup)"}
COMMONS = "https://commons.wikimedia.org/w/api.php"
MARK = re.compile(r"\b(logo|seal|emblem|crest|wordmark|logotype)\b", re.I)
OLD = re.compile(r"\b(old|former|historic|vintage|19\d\d|200\d|201[0-5])\b", re.I)
BANNED = re.compile(r"(gettyimages|apimages|apnews|reuters|shutterstock|alamy|istockphoto|dreamstime|sportzpics|ptinews|"
                    r"depositphotos|123rf|imago-images|pressassociation|afp\.com|epa\.eu)", re.I)


def slug(name):
    return re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")


def _get(params):
    url = COMMONS + "?" + urllib.parse.urlencode(dict(params, format="json"))
    return json.load(urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30))


def licence_ok(short):
    s = (short or "").strip().lower()
    return s.startswith("public domain") or s.startswith("pd") or s.startswith("cc0") or bool(re.match(r"^cc by(-sa)? \d", s))


def needs_credit(licence):
    return bool(re.match(r"^cc by", (licence or "").lower()))


def commons_logo(entity):
    hits = []
    for q in (f'"{entity}" logo', f'"{entity}" seal OR emblem OR crest OR wordmark'):
        hits += _get({"action": "query", "list": "search", "srnamespace": 6, "srlimit": 12, "srsearch": q})["query"]["search"]
    words = [w for w in re.findall(r"[a-z0-9]+", entity.lower()) if len(w) > 1]

    def rank(h):
        t = h["title"].lower()
        return (-sum(w in t for w in words), not MARK.search(t), bool(OLD.search(t)), not t.endswith(".svg"))
    seen = set()
    for h in sorted(hits, key=rank):
        t = h["title"].lower()
        if t in seen or not all(w in t for w in words) or not MARK.search(t): continue
        seen.add(t)
        info = _get({"action": "query", "titles": h["title"], "prop": "imageinfo", "iiprop": "url|extmetadata|mime|size", "iiurlwidth": 1600})
        page = next(iter(info["query"]["pages"].values())); ii = (page.get("imageinfo") or [{}])[0]
        meta = ii.get("extmetadata", {}); lic = meta.get("LicenseShortName", {}).get("value", "")
        if not licence_ok(lic): continue
        src = ii.get("thumburl") or ii.get("url")
        if not src: continue
        return {"url": src, "orig": ii.get("url"), "page": ii.get("descriptionurl"), "licence": lic, "title": h["title"],
                "artist": re.sub("<[^>]+>", "", meta.get("Artist", {}).get("value", ""))[:200]}
    return None


def download(url, dest, fallback=None):
    """Fetch an image to dest as PNG/JPG (SVG rendered at 2000 px). Refuses agency/stock hosts. Tries `fallback` on HTTP errors."""
    if BANNED.search(url): raise ValueError(f"refusing agency/stock source {url}")
    try:
        data = urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=60).read()
    except urllib.error.HTTPError:
        if not fallback or fallback == url: raise
        return download(fallback, dest)
    dest = pathlib.Path(dest); dest.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory() as tmp:
        raw = pathlib.Path(tmp) / "raw"; raw.write_bytes(data)
        if data[:200].lstrip().startswith((b"<svg", b"<?xml")) or url.lower().split("?")[0].endswith(".svg"):
            subprocess.run(["rsvg-convert", "-w", "2000", "-o", str(dest), str(raw)], check=True)
        else:
            im = Image.open(raw); im.load()
            (im.convert("RGBA") if dest.suffix == ".png" else im.convert("RGB")).save(dest)
    return dest


def official_image(entity, what, site=None, hint=""):
    """Ask Codex (web search) for the direct URL of an official image on the entity's own site / press kit / newsroom."""
    r = llm.ask_json(
        f'Use web search. Find the direct file URL of {what} of "{entity}", published by {entity} itself: its official website, '
        f"newsroom / press room, or media / brand kit{f' (official site: {site})' if site else ''}. For logos prefer SVG or the largest "
        "transparent PNG; for press images the largest JPG/PNG. Never news sites, stock or agency photos (Getty, AP, Reuters, PTI, "
        "Shutterstock), fan sites, social media or search-engine caches.\nReply ONLY JSON: {\"image_url\": \"https://...\", "
        "\"page_url\": \"the official page listing it\", \"owner_domain\": \"example.com\", \"terms\": \"usage terms stated, if any\"} "
        "or {\"image_url\": null, \"why\": \"...\"}" + (f"\nA previous candidate was rejected: {hint} Find the CURRENT one." if hint else ""),
        search=True, timeout=600)
    url, page, dom = r.get("image_url"), r.get("page_url") or "", (r.get("owner_domain") or "").lower().removeprefix("www.")
    if not url or not dom: return None
    host = urllib.parse.urlparse(page).hostname or ""
    if not (host == dom or host.endswith("." + dom)) or BANNED.search(url): return None   # listed on the entity's own site
    return {"url": url, "page": page, "licence": f"official ({dom}){'; ' + r['terms'] if r.get('terms') else ''}"[:300]}


def verify(entity, path, what="official logo", site=None):
    """Vision check before anything enters the graph: is this really that entity's current mark (not a namesake's)?"""
    e = graph.find_entity(entity) or {}
    site = site or e.get("official_site"); company = e.get("company")
    r = llm.ask_json(f'Look at the attached image. Is it the {what} of "{entity}"'
                     f'{f" (owned by {company})" if company else ""}{f", whose website is {site}" if site else ""}? It must be the mark that '
                     "entity itself uses today, not a different organisation with a similar name (a sports club, a namesake company "
                     "abroad), not fan-made, not an outdated version. Reply ONLY JSON: {\"match\": true or false, \"why\": \"one line\"}",
                     images=[path], timeout=300)
    return bool(r.get("match")), r.get("why", "")


def logo(entity, dest, official_site=None, item_id=None):
    """The official logo for `entity` at dest. Returns the graph asset (with licence/credit), or None when none was found.
    New logos are vision-checked before they enter the graph; the brand's own site goes first when we know it."""
    have = graph.assets_of(entity, "logo")
    if not have:
        site = official_site or (graph.find_entity(entity) or {}).get("official_site")
        hint = []
        sources = [lambda: official_image(entity, "the official logo", site), lambda: commons_logo(entity),
                   lambda: official_image(entity, "the current official logo", site, hint[-1]) if hint else None]
        if not site: sources[0], sources[1] = sources[1], sources[0]
        for get in sources:
            try:
                found = get()
            except Exception:
                found = None
            if not found: continue
            with tempfile.TemporaryDirectory() as tmp:
                try:
                    f = download(found["url"], pathlib.Path(tmp) / f"{slug(entity)}.png", found.get("orig"))
                except Exception:
                    continue
                ok, why = verify(entity, f, "official logo", site)
                if not ok:
                    hint.append(why); continue
                credit = f"{entity} logo: {found.get('artist') or 'Wikimedia Commons'}, {found['licence']}" if needs_credit(found["licence"]) else ""
                have = [graph.add_asset(f, "logo", [graph.entity(entity, official_site=site)], title=f"{entity} logo",
                                        source_url=found["url"], source_page=found.get("page", ""), licence=found["licence"], credit=credit)]
                break
        if not have: return None
    a = have[0]; Image.open(a["path"]).save(dest); graph.used(a["id"], item_id)
    return a


def press(entity, subject, dest, official_site=None, item_id=None):
    """An official press / newsroom image of `subject` (e.g. "iPhone 18 Pro product shot") from `entity`."""
    hit = graph.similar(f"{entity} {subject}", kinds=("press",), threshold=0.45)
    if not hit:
        found = official_image(entity, f"an official press image of {subject}", official_site)
        if not found: return None
        with tempfile.TemporaryDirectory() as tmp:
            f = download(found["url"], pathlib.Path(tmp) / f"{slug(subject)}.jpg")
            ok, why = verify(entity, f, f"official press image of {subject}", official_site)
            if not ok: return None
            hit = graph.add_asset(f, "press", [graph.entity(entity, official_site=official_site)], title=subject, tags=f"{entity} {subject}",
                                  source_url=found["url"], source_page=found["page"], licence=found["licence"])
    im = Image.open(hit["path"]); (im.convert("RGB") if str(dest).endswith(".jpg") else im).save(dest); graph.used(hit["id"], item_id)
    return hit


NOISE = {"wikimedia", "commons", "flickr", "openverse", "unsplash", "pexels", "pixabay", "cc", "by", "sa", "license", "licence",
         "photo", "image", "file", "public", "domain", "archive", "credit", "jpg", "png"}


def clean_query(query):
    """Drop source/licence words a writer sometimes puts in a search ("Kohli batting Wikimedia CC BY 2.0" -> "Kohli batting")."""
    return " ".join(w for w in re.findall(r"[\w'-]+", query) if w.lower() not in NOISE and not re.fullmatch(r"\d+(\.\d+)?", w))


def proper_names(query):
    """Capitalised words of the query (names of people, places, teams) that a matching photo must mention."""
    return [w.lower() for w in re.findall(r"\b[A-Z][a-zA-Z'-]+", clean_query(query)) if w.lower() not in NOISE]


def commons_photo(query):
    """A real photo on Wikimedia Commons (public domain, CC0, CC BY, CC BY-SA), best match first; logos/diagrams skipped."""
    hits = _get({"action": "query", "list": "search", "srnamespace": 6, "srlimit": 15, "srsearch": f"{query} filetype:bitmap"})["query"]["search"]
    words = [w for w in re.findall(r"[a-z0-9]+", query.lower()) if len(w) > 2]
    hits.sort(key=lambda h: (-sum(w in h["title"].lower() for w in words), bool(OLD.search(h["title"]))))
    names = proper_names(query)
    for h in hits[:8]:
        t = h["title"].lower()
        if MARK.search(t) or t.endswith((".svg", ".gif", ".pdf", ".tif", ".tiff")) or sum(w in t for w in words) < max(1, len(words) // 2): continue
        if names and not all(n in t for n in names): continue      # a named person/place must be the one in the photo
        info = _get({"action": "query", "titles": h["title"], "prop": "imageinfo", "iiprop": "url|extmetadata|size", "iiurlwidth": 1600})
        page = next(iter(info["query"]["pages"].values())); ii = (page.get("imageinfo") or [{}])[0]
        meta = ii.get("extmetadata", {}); lic = meta.get("LicenseShortName", {}).get("value", "")
        if not licence_ok(lic) or (ii.get("width") or 0) < 800: continue
        artist = re.sub("<[^>]+>", "", meta.get("Artist", {}).get("value", "")).strip()[:120] or "Wikimedia Commons"
        return {"url": ii.get("thumburl") or ii.get("url"), "orig": ii.get("url"), "page": ii.get("descriptionurl"), "licence": lic,
                "artist": artist, "title": h["title"].removeprefix("File:")}
    return None


def openverse_photo(query):
    """A real photo from Openverse (Flickr and other open collections) under CC BY, CC BY-SA, CC0 or public domain."""
    url = "https://api.openverse.org/v1/images/?" + urllib.parse.urlencode({"q": query, "license": "by,by-sa,cc0,pdm", "page_size": 12,
                                                                             "mature": "false"})
    res = json.load(urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30)).get("results", [])
    names = proper_names(query)
    for r in res:
        if BANNED.search(r.get("url", "") + r.get("foreign_landing_url", "")) or (r.get("width") or 0) < 800: continue
        text = " ".join([r.get("title") or ""] + [x.get("name", "") for x in r.get("tags") or []]).lower()
        if names and not all(n in text for n in names): continue
        lic = f"CC {r['license'].upper()} {r.get('license_version') or ''}".strip() if r["license"] not in ("cc0", "pdm") else \
            ("CC0" if r["license"] == "cc0" else "Public domain")
        return {"url": r["url"], "page": r.get("foreign_landing_url"), "licence": lic, "artist": (r.get("creator") or "unknown")[:120],
                "title": (r.get("title") or query)[:120]}
    return None


def _keys():
    from . import tg
    try:
        return tg.env()
    except Exception:
        return {}


def stock_photo(query):
    """A real stock photo of a generic subject (stadium, phone, office, food, skyline) from Unsplash, Pexels or Pixabay —
    their licences allow commercial use without payment. Needs the free API keys in /opt/studio/.env; skipped without them."""
    k = _keys(); q = urllib.parse.quote(query)

    def get(url, headers=None):
        return json.load(urllib.request.urlopen(urllib.request.Request(url, headers={**UA, **(headers or {})}), timeout=30))
    try:
        if k.get("UNSPLASH_ACCESS_KEY"):
            r = get(f"https://api.unsplash.com/search/photos?query={q}&per_page=5&orientation=portrait&content_filter=high",
                    {"Authorization": f"Client-ID {k['UNSPLASH_ACCESS_KEY']}", "Accept-Version": "v1"})
            for p in r.get("results", []):
                u = p["user"]
                try:   # Unsplash API terms: report the download
                    get(p["links"]["download_location"], {"Authorization": f"Client-ID {k['UNSPLASH_ACCESS_KEY']}"})
                except Exception:
                    pass
                return {"url": p["urls"]["regular"], "page": p["links"]["html"], "licence": "Unsplash License",
                        "artist": u.get("name", "Unsplash"), "title": (p.get("alt_description") or query)[:100], "credit_style": "Unsplash"}
        if k.get("PEXELS_API_KEY"):
            r = get(f"https://api.pexels.com/v1/search?query={q}&per_page=5&orientation=portrait", {"Authorization": k["PEXELS_API_KEY"]})
            for p in r.get("photos", []):
                return {"url": p["src"]["large2x"], "page": p["url"], "licence": "Pexels License", "artist": p.get("photographer", "Pexels"),
                        "title": (p.get("alt") or query)[:100], "credit_style": "Pexels"}
        if k.get("PIXABAY_API_KEY"):
            r = get(f"https://pixabay.com/api/?key={k['PIXABAY_API_KEY']}&q={q}&image_type=photo&orientation=vertical&safesearch=true&per_page=5")
            for p in r.get("hits", []):
                return {"url": p["largeImageURL"], "page": p["pageURL"], "licence": "Pixabay Content License", "artist": p.get("user", "Pixabay"),
                        "title": (p.get("tags") or query)[:100], "credit_style": "Pixabay"}
    except Exception:
        return None
    return None


def photo(query, dest, entity=None, item_id=None):
    """A real, openly licensed photo (credited in the caption): graph -> Wikimedia Commons -> Openverse (named subjects) or
    Unsplash / Pexels / Pixabay (generic subjects)."""
    query = clean_query(query)
    hit = graph.similar(query, kinds=("photo",), threshold=0.5)
    if not hit:
        named = bool(proper_names(query))   # a named person/place/team: open-licence archives; a generic subject: stock first
        found = (commons_photo(query) or openverse_photo(query)) if named else (stock_photo(query) or commons_photo(query) or openverse_photo(query))
        if not found: return None
        with tempfile.TemporaryDirectory() as tmp:
            f = download(found["url"], pathlib.Path(tmp) / f"{slug(query)[:50]}.jpg", found.get("orig"))
            credit = (f"{found['title']}: {found['artist']}, {found['licence']}" if needs_credit(found["licence"]) else
                      f"{found['artist']} on {found['credit_style']}" if found.get("credit_style") else "")   # stock: a courtesy credit
            ents = [graph.entity(entity)] if entity else []
            hit = graph.add_asset(f, "photo", ents, title=found["title"][:80], tags=query, source_url=found["url"], source_page=found.get("page", ""),
                                  licence=found["licence"], credit=credit)
    im = Image.open(hit["path"]); (im.convert("RGB") if str(dest).endswith(".jpg") else im).save(dest); graph.used(hit["id"], item_id)
    return hit


BROWSER = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0 Safari/537.36",
           "Accept-Language": "en-IN,en;q=0.9"}
IMG_URL = re.compile(r"""https?://[^\s"'<>()\\]+?\.(?:jpe?g|png|webp)(?:\?[^\s"'<>()\\]*)?""", re.I)
NOT_PHOTO = re.compile(r"(logo|icon|sprite|avatar|favicon|badge|button|placeholder|pixel|1x1|spacer|emoji|flag-|social|share-|"
                       r"thumb-small|author|profile-pic|qr)", re.I)


def page_images(url, limit=60):
    """Candidate image URLs on one page: og/twitter images, <img>/<source> src/srcset (largest), and image URLs in inline data."""
    req = urllib.request.Request(url, headers=BROWSER)
    html = urllib.request.urlopen(req, timeout=30).read(4_000_000).decode("utf-8", "replace")
    found = re.findall(r'<meta[^>]+(?:property|name)=["\'](?:og:image|twitter:image)(?::src)?["\'][^>]*content=["\']([^"\']+)', html, re.I)
    for tag in re.findall(r"<(?:img|source)\b[^>]*>", html, re.I):
        for attr in ("srcset", "data-srcset"):
            m = re.search(attr + r'=["\']([^"\']+)', tag, re.I)
            if m:   # the largest candidate of a srcset
                parts = [x.strip().split() for x in m.group(1).split(",") if x.strip()]
                best = max(parts, key=lambda x: float(re.sub(r"[^\d.]", "", x[1]) or 0) if len(x) > 1 else 0)
                found.append(best[0])
        for attr in ("data-src", "src"):
            m = re.search(r"\b" + attr + r'=["\']([^"\']+)', tag, re.I)
            if m: found.append(m.group(1))
    found += IMG_URL.findall(html.replace("\\/", "/"))
    out, seen = [], set()
    for u in found:
        u = urllib.parse.urljoin(url, u.replace("&amp;", "&").strip())
        key = u.split("?")[0]
        if not u.startswith("http") or key in seen or NOT_PHOTO.search(key.rsplit("/", 1)[-1]) or BANNED.search(u): continue
        if key.lower().endswith((".svg", ".gif", ".ico")): continue
        seen.add(key); out.append(u)
    return out[:limit]


def _ahash(im):
    g = np.asarray(im.convert("L").resize((12, 12)), dtype=np.float32)
    return (g > g.mean()).flatten()


def official_gallery(research, item_id=None, want=10):
    """Real images for a story from its OFFICIAL pages (the entities' own sites): screenshots, product shots, key art, official
    photos. Vision-labelled (relevant? logo? watermark? text-heavy?) and registered in the graph (kind "press") so later posts
    reuse them. Returns [{"id", "path", "what", "kind", "w", "h", "text_heavy", "entity", "owner", "page"}] (graph ids)."""
    from concurrent.futures import ThreadPoolExecutor
    ents = research.get("entities") or []
    doms = {}
    for e in ents:
        h = (urllib.parse.urlparse(e.get("official_site") or "").hostname or "").removeprefix("www.")
        if h: doms[h] = e
    def owner_of(u):
        h = (urllib.parse.urlparse(u).hostname or "").removeprefix("www.")
        return next((e for d, e in doms.items() if h == d or h.endswith("." + d) or d.endswith("." + h)), None)
    listed = [u for u in research.get("official_pages") or [] if isinstance(u, str) and u.startswith("http") and not BANNED.search(u)]
    main = ents[0] if ents else {}
    def owner_of(u, _o=owner_of):   # a page research listed as official (e.g. Xbox Wire for Minecraft) counts for the main entity
        return _o(u) or (main if u in listed else None)
    pages = listed + [s["url"] for f in research.get("facts", []) for s in f.get("sources", []) if s.get("url") and owner_of(s["url"])]
    pages = list(dict.fromkeys(pages))[:5]
    have = []   # what the graph already holds for these entities (vetted before): reuse first
    for e in ents:
        for a in graph.assets_of(e["name"], "press")[:6]:
            have.append({"id": a["id"], "path": a["path"], "what": a["title"], "kind": "press", "entity": e["name"], "owner": e.get("company") or e["name"],
                         "page": a.get("source_page", ""), "text_heavy": False, **dict(zip(("w", "h"), Image.open(a["path"]).size))})
    cands = []
    for pg in pages:
        try:
            cands += [(u, pg) for u in page_images(pg)]
        except Exception:
            continue
    tmp = pathlib.Path(tempfile.mkdtemp(prefix="gallery-"))

    def fetch(k_u):
        k, (u, pg) = k_u
        try:
            data = urllib.request.urlopen(urllib.request.Request(u, headers=BROWSER), timeout=30).read(15_000_000)
            im = Image.open(__import__("io").BytesIO(data)); im.load(); im = im.convert("RGB")
            w, h = im.size
            if w < 700 or h < 380 or not 0.33 < w / h < 3.2: return None
            f = tmp / f"c{k:02d}.jpg"; im.save(f, quality=93)
            return {"path": str(f), "url": u, "page": pg, "w": w, "h": h, "hash": _ahash(im)}
        except Exception:
            return None
    with ThreadPoolExecutor(8) as ex: got = [g for g in ex.map(fetch, enumerate(cands[:60])) if g]
    uniq = []
    for g in sorted(got, key=lambda g: -g["w"] * g["h"]):
        if all((g["hash"] != u["hash"]).sum() > 14 for u in uniq): uniq.append(g)
    uniq = uniq[:12]
    topic = research.get("topic", ""); keep = []
    for i in range(0, len(uniq), 6):
        batch = uniq[i:i + 6]
        try:
            r = llm.ask_json(
                f'These {len(batch)} images come from the official pages of the story "{topic}" ({", ".join(e["name"] for e in ents[:4])}). '
                "For each image (1 = first attached) say whether it is usable in an Instagram news post about this story: it must show the "
                "story's real subject (the product, game, app, screen, place, event or person), not a logo, icon, generic stock filler, "
                "ad banner for something else, or a third-party watermark (Getty, AP, Reuters, a news site). Reply ONLY JSON: "
                '{"images": [{"i": 1, "keep": true, "kind": "screenshot|product|keyart|person|place|event|chart|logo|other", '
                '"what": "what it shows, max 12 words", "text_heavy": false, "watermark": false}]}', images=[b["path"] for b in batch], timeout=600)
        except Exception:
            continue
        for v in r.get("images", []):
            k = (v.get("i") or 0) - 1
            if not 0 <= k < len(batch) or not v.get("keep") or v.get("watermark") or v.get("kind") in ("logo", "other"): continue
            keep.append(dict(batch[k], what=(v.get("what") or topic)[:90], kind=v.get("kind"), text_heavy=bool(v.get("text_heavy"))))
    out = list(have)
    for g in keep[:want]:
        e = owner_of(g["page"]) or {}
        dom = (urllib.parse.urlparse(g["page"]).hostname or "").removeprefix("www.")
        ent = [graph.entity(e["name"], official_site=e.get("official_site"))] if e.get("name") else []
        a = graph.add_asset(g["path"], "press", ent, title=g["what"], tags=f"{topic} {g['what']} {g['kind']}", source_url=g["url"],
                            source_page=g["page"], licence=f"official ({dom}) — editorial use")
        graph.used(a["id"], item_id)
        out.append({"id": a["id"], "path": a["path"], "what": g["what"], "kind": g["kind"], "w": g["w"], "h": g["h"], "text_heavy": g["text_heavy"],
                    "entity": e.get("name", ""), "owner": e.get("company") or e.get("name", dom), "page": g["page"]})
    seen, final = set(), []
    for x in out:
        if x["id"] not in seen: seen.add(x["id"]); final.append(x)
    return final


def flag(country, dest, item_id=None):
    """A national flag (public domain SVG from Wikimedia Commons, "Flag of <country>.svg"), graph first."""
    have = graph.assets_of(country, "flag")
    if not have:
        name = f"File:Flag of {country}.svg"
        info = _get({"action": "query", "titles": name, "prop": "imageinfo", "iiprop": "url|extmetadata", "iiurlwidth": 1600, "redirects": 1})
        page = next(iter(info["query"]["pages"].values())); ii = (page.get("imageinfo") or [{}])[0]
        if not ii.get("url"): return None
        with tempfile.TemporaryDirectory() as tmp:
            f = download(ii["url"], pathlib.Path(tmp) / f"flag-{slug(country)}.png")
            have = [graph.add_asset(f, "flag", [graph.entity(country, "country")], title=f"Flag of {country}", source_url=ii["url"],
                                    source_page=ii.get("descriptionurl", ""), licence="Public domain")]
    a = have[0]; Image.open(a["path"]).save(dest); graph.used(a["id"], item_id)
    return a


def codex_image(out, brief, refs=(), size="1024x1536"):
    out = pathlib.Path(out)
    if out.exists(): return out
    cmd = ["bash", str(TOOLS / "codex-image.sh"), "-o", str(out), "-s", size]
    for r in list(refs)[:5]: cmd += ["-i", str(r)]
    p = subprocess.run(cmd, input=brief, text=True, capture_output=True, timeout=1500)
    if not out.exists(): raise RuntimeError(f"image generation failed for {out.name}: {p.stderr[-600:]}")
    return out


def cut_green(src, dest):
    """Key out a flat green background, soften the edge, remove green spill, trim to the object."""
    a = np.asarray(Image.open(src).convert("RGB")).astype(np.float32)
    r, g, b = a[..., 0], a[..., 1], a[..., 2]
    green = g - np.maximum(r, b)
    alpha = np.clip(1 - (green - 30) / 70, 0, 1)
    a[..., 1] = np.where(green > 0, np.minimum(g, np.maximum(r, b) + 10), g)
    im = Image.fromarray(np.dstack([a, alpha * 255]).astype(np.uint8), "RGBA"); box = im.getbbox()
    (im.crop(box) if box else im).save(dest)
    return dest


def object_image(dest, prompt, item_id=None):
    """A generic object cut-out: reused from the graph when we already made a similar one, else generated and registered."""
    hit = graph.similar(prompt, kinds=("object",))
    if not hit:
        raw = pathlib.Path(dest).with_suffix(".raw.png")
        codex_image(raw, f"{prompt}. Photoreal, sharp studio lighting, the object centred and filling most of the frame, on a flat pure "
                         "chroma-key green #00FF00 background with no shadow, no floor, no text, no logos, no people.", size="1024x1024")
        cut = cut_green(raw, pathlib.Path(dest).with_suffix(".cut.png"))
        hit = graph.add_asset(cut, "object", title=prompt[:60], tags=prompt, prompt=prompt, licence="own (generated)")
    Image.open(hit["path"]).save(dest); graph.used(hit["id"], item_id)
    return hit


def contact_sheets(video, out_dir, per_sheet=12, cols=6):
    out_dir = pathlib.Path(out_dir); out_dir.mkdir(parents=True, exist_ok=True)
    for f in out_dir.glob("f-*.jpg"): f.unlink()
    subprocess.run(["ffmpeg", "-v", "error", "-y", "-i", str(video), "-vf", "fps=1,scale=270:480", str(out_dir / "f-%03d.jpg")], check=True)
    frames = sorted(out_dir.glob("f-*.jpg")); sheets = []
    try:
        font = ImageFont.truetype("DejaVuSans-Bold.ttf", 22)
    except OSError:
        font = ImageFont.load_default()
    for k in range(0, len(frames), per_sheet):
        chunk = frames[k:k + per_sheet]; rows = (len(chunk) + cols - 1) // cols
        sheet = Image.new("RGB", (cols * 280, rows * 520), "white"); d = ImageDraw.Draw(sheet)
        for j, f in enumerate(chunk):
            x, y = (j % cols) * 280 + 5, (j // cols) * 520 + 5
            sheet.paste(Image.open(f), (x, y)); d.text((x + 4, y + 484), f"{k + j}s", fill="black", font=font)
        p = out_dir / f"sheet-{k // per_sheet + 1}.jpg"; sheet.save(p, quality=85); sheets.append(p)
    return sheets
